// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startSearch: (request: SearchRequest) => typedError<RunSummary, AppError>(__TAURI_INVOKE("start_search", { request })),
	cancelSearch: () => typedError<boolean, AppError>(__TAURI_INVOKE("cancel_search")),
	recentResults: (limit: number) => typedError<Organization[], AppError>(__TAURI_INVOKE("recent_results", { limit })),
	recentRuns: (limit: number) => typedError<SearchRunInfo[], AppError>(__TAURI_INVOKE("recent_runs", { limit })),
	resultsForRun: (runId: string, limit: number) => typedError<Organization[], AppError>(__TAURI_INVOKE("results_for_run", { runId, limit })),
	exportResults: (runId: string, format: ExportFormat, limit: number) => typedError<ExportReceipt, AppError>(__TAURI_INVOKE("export_results", { runId, format, limit })),
	health: () => __TAURI_INVOKE<HealthInfo>("health"),
};

/* Types */
export type AppError = {
	kind: ErrorKind,
	message: string,
	retryable: boolean,
};

export type ErrorKind = "validation" | "network" | "rateLimited" | "blocked" | "parse" | "storage" | "export" | "cancelled" | "internal";

export type ExportFormat = "csv" | "json" | "xlsx";

export type ExportReceipt = {
	path: string,
	rows: number,
	format: ExportFormat,
};

export type HealthInfo = {
	appVersion: string,
	provider: string,
	browserEngine: string,
	apiKeyRequired: boolean,
	availableSources: SourceKind[],
};

export type SourceKind = "twoGis" | "yell" | "zoon" | "rusprofile";

export type SourceAttribution = {
	source: SourceKind,
	sourceId: string,
	sourceUrl: string,
	collectedAt: string,
};

export type LeadBranch = {
	address: string,
	latitude: number | null,
	longitude: number | null,
	source: SourceKind,
};

export type DedupeInfo = {
	mergedRecords: number,
	fingerprint: string,
	possibleDuplicate: boolean,
};

export type Organization = {
	id: string,
	name: string,
	category: string | null,
	address: string | null,
	rating: number | null,
	reviewCount: number | null,
	phones: string[],
	email: string | null,
	website: string | null,
	socials: string[],
	openingStatus: string | null,
	latitude: number | null,
	longitude: number | null,
	sourceUrl: string,
	collectedAt: string,
	inn: string | null,
	ogrn: string | null,
	sources: SourceAttribution[],
	tags: string[],
	branches: LeadBranch[],
	dedupe: DedupeInfo,
};

export type RunSummary = {
	runId: string,
	startedAt: string,
	finishedAt: string,
	organizations: Organization[],
	warnings: string[],
	rawRecords: number,
	duplicatesMerged: number,
};

export type SearchRunInfo = {
	runId: string,
	startedAt: string,
	finishedAt: string,
	request: SearchRequest,
	warnings: string[],
	rawRecords: number,
	duplicatesMerged: number,
	organizationCount: number,
};

export type SearchRequest = {
	region: string,
	query: string,
	maxResults: number,
	maxPages: number,
	concurrency: number,
	requestDelayMs: number,
	sources: SourceKind[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
