// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	startSearch: (request: SearchRequest) => typedError<RunSummary, AppError>(__TAURI_INVOKE("start_search", { request })),
	resumeSearch: (jobId: string) => typedError<RunSummary, AppError>(__TAURI_INVOKE("resume_search", { jobId })),
	pauseProvider: (source: SourceKind) => typedError<boolean, AppError>(__TAURI_INVOKE("pause_provider", { source })),
	resumeProvider: (source: SourceKind) => typedError<boolean, AppError>(__TAURI_INVOKE("resume_provider", { source })),
	cancelSearch: () => typedError<boolean, AppError>(__TAURI_INVOKE("cancel_search")),
	recentResults: (limit: number) => typedError<Organization[], AppError>(__TAURI_INVOKE("recent_results", { limit })),
	recentRuns: (limit: number) => typedError<SearchRunInfo[], AppError>(__TAURI_INVOKE("recent_runs", { limit })),
	recentCollectionJobs: (limit: number) => typedError<CollectionJobInfo[], AppError>(__TAURI_INVOKE("recent_collection_jobs", { limit })),
	resultsForRun: (runId: string, limit: number) => typedError<Organization[], AppError>(__TAURI_INVOKE("results_for_run", { runId, limit })),
	resultsForRunPage: (runId: string, offset: number, limit: number) => typedError<RunResultsPage, AppError>(__TAURI_INVOKE("results_for_run_page", { runId, offset, limit })),
	exportResults: (runId: string, format: ExportFormat) => typedError<ExportReceipt, AppError>(__TAURI_INVOKE("export_results", { runId, format })),
	health: () => __TAURI_INVOKE<HealthInfo>("health"),
	save2gisApiKey: (key: string) => typedError<boolean, AppError>(__TAURI_INVOKE("save_2gis_api_key", { key })),
	delete2gisApiKey: () => typedError<boolean, AppError>(__TAURI_INVOKE("delete_2gis_api_key")),
	twoGisApiKeySaved: () => __TAURI_INVOKE<boolean>("two_gis_api_key_saved"),
};

/* Types */
export type AppError = {
	kind: ErrorKind,
	message: string,
	retryable: boolean,
	retryAfterSeconds?: number | null,
	diagnostics?: ResponseDiagnostics | null,
};

export type CollectionJobInfo = {
	jobId: string,
	state: CollectionJobState,
	request: SearchRequest,
	startedAt: string,
	updatedAt: string,
	message: string,
	completedTargets: number,
	totalTargets: number,
};

export type CollectionJobState = "running" | "paused" | "completed" | "partial" | "failed" | "interrupted" | "cancelled";

export type CollectionPreset = "gentle" | "normal" | "custom";

export type DedupeInfo = {
	mergedRecords: number,
	fingerprint: string,
	possibleDuplicate: boolean,
};

export type ErrorKind = "validation" | "network" | "rateLimited" | "blocked" | "captchaRequired" | "challengeRequired" | "parse" | "storage" | "export" | "cancelled" | "internal";

export type ExportFormat = "csv" | "json" | "xlsx";

export type ExportReceipt = {
	path: string,
	rows: number,
	format: ExportFormat,
};

export type HealthInfo = {
	appVersion: string,
	provider: string,
	browserEngine: string,
	apiKeyRequired: boolean,
	availableSources: SourceKind[],
};

export type LeadBranch = {
	address: string,
	latitude: number | null,
	longitude: number | null,
	source: SourceKind,
};

export type Organization = {
	id: string,
	name: string,
	category: string | null,
	address: string | null,
	rating: number | null,
	reviewCount: number | null,
	phones: string[],
	email: string | null,
	website: string | null,
	socials: string[],
	openingStatus: string | null,
	latitude: number | null,
	longitude: number | null,
	sourceUrl: string,
	collectedAt: string,
	inn?: string | null,
	ogrn?: string | null,
	sources?: SourceAttribution[],
	tags?: string[],
	branches?: LeadBranch[],
	dedupe?: DedupeInfo,
};

export type ProviderSearchConfig = {
	source: SourceKind,
	enabled: boolean,
	maxResults: number,
	maxPages: number,
	concurrency: number,
	requestDelayMs: number,
	preset: CollectionPreset,
	maxRetries: number,
	backoffBaseSeconds: number,
};

export type ResponseDiagnostics = {
	source: SourceKind,
	httpStatus: number | null,
	requestUrl: string,
	finalUrl: string | null,
	pageTitle: string | null,
	reason: string,
};

export type RunResultsPage = {
	runId: string,
	items: Organization[],
	offset: number,
	limit: number,
	total: number,
};

export type RunSummary = {
	runId: string,
	startedAt: string,
	finishedAt: string,
	organizations: Organization[],
	warnings: string[],
	rawRecords: number,
	duplicatesMerged: number,
	organizationCount: number,
};

export type SearchRequest = {
	region: string,
	query: string,
	maxResults: number,
	maxPages: number,
	concurrency: number,
	requestDelayMs: number,
	sources?: SourceKind[],
	regions?: string[],
	providerConfigs?: ProviderSearchConfig[],
};

export type SearchRunInfo = {
	runId: string,
	startedAt: string,
	finishedAt: string,
	request: SearchRequest,
	warnings: string[],
	rawRecords: number,
	duplicatesMerged: number,
	organizationCount: number,
};

export type SourceAttribution = {
	source: SourceKind,
	sourceId: string,
	sourceUrl: string,
	collectedAt: string,
};

export type SourceKind = "twoGis" | "yell" | "zoon" | "rusprofile";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
